#Khai báo thư viện
from tkinter import *
import math
from tkinter.ttk import *
import tkinter
import cv2
import matplotlib.pyplot as plt
import PIL.Image,PIL.ImageTk
from djitellopy import tello
import sqlite3
import Face
import numpy as np

video = cv2.VideoCapture(0)

# #Kết nối với Drone
# datn = tello.Tello()
# datn.connect()
# print(datn.get_battery()) # Hiển thị % pin hiện tại
# # Lệnh cất cánh
# datn.takeoff()
# #Lệnh bật camera của drone
# datn.streamon()
# speed = 20

#Tạo cửa sổ giao diện với thư viện tkinter


# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("800x600")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 600,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    400.0,
    300.0,
    image=image_image_1
)

canvas.create_rectangle(
    150.0,
    59.0,
    650.0,
    409.0,
    fill="#D9D9D9",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=682.0,
    y=269.0,
    width=99.0,
    height=31.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=682.0,
    y=213.0,
    width=99.0,
    height=31.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=682.0,
    y=161.0,
    width=99.0,
    height=31.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=682.0,
    y=109.0,
    width=99.0,
    height=31.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=150.0,
    y=475.0,
    width=99.0,
    height=31.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=51.0,
    y=516.0,
    width=99.0,
    height=31.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=249.0,
    y=516.0,
    width=99.0,
    height=31.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_8 clicked"),
    relief="flat"
)
button_8.place(
    x=150.0,
    y=559.0,
    width=99.0,
    height=31.0
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_9 clicked"),
    relief="flat"
)
button_9.place(
    x=547.0,
    y=475.0,
    width=99.0,
    height=31.0
)

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_10 clicked"),
    relief="flat"
)
button_10.place(
    x=448.0,
    y=516.0,
    width=99.0,
    height=31.0
)

button_image_11 = PhotoImage(
    file=relative_to_assets("button_11.png"))
button_11 = Button(
    image=button_image_11,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_11 clicked"),
    relief="flat"
)
button_11.place(
    x=646.0,
    y=516.0,
    width=99.0,
    height=31.0
)

button_image_12 = PhotoImage(
    file=relative_to_assets("button_12.png"))
button_12 = Button(
    image=button_image_12,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_12 clicked"),
    relief="flat"
)
button_12.place(
    x=547.0,
    y=559.0,
    width=99.0,
    height=31.0
)

button_image_13 = PhotoImage(
    file=relative_to_assets("button_13.png"))
button_13 = Button(
    image=button_image_13,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_13 clicked"),
    relief="flat"
)
button_13.place(
    x=162.0,
    y=426.0,
    width=99.0,
    height=30.0
)

button_image_14 = PhotoImage(
    file=relative_to_assets("button_14.png"))
button_14 = Button(
    image=button_image_14,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_14 clicked"),
    relief="flat"
)
button_14.place(
    x=288.0,
    y=426.0,
    width=99.0,
    height=30.0
)

button_image_15 = PhotoImage(
    file=relative_to_assets("button_15.png"))
button_15 = Button(
    image=button_image_15,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_15 clicked"),
    relief="flat"
)
button_15.place(
    x=414.0,
    y=426.0,
    width=99.0,
    height=30.0
)

button_image_16 = PhotoImage(
    file=relative_to_assets("button_16.png"))
button_16 = Button(
    image=button_image_16,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_16 clicked"),
    relief="flat"
)
button_16.place(
    x=540.0,
    y=426.0,
    width=99.0,
    height=30.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    74.0,
    73.0,
    image=image_image_2
)
window.resizable(False, False)



#Khai báo các biến nút bấm
btn1, btn2, btn3, btn4, btnu, btnd, btnf, btnb, btnl, btnr, btny, btnv, btns,\
btnm, btna, btng = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

#Các chương trình của nút bấm
def FindFace():
    global btn1
    btn1 = 1 - btn1
def FaceMesh():
    global btn2
    btn2 = 1 - btn2
def FindHands():
    global btn3
    btn3 = 1 - btn3
def FindPose():
    global btn4
    btn4 = 1 - btn4
def Up():
    global btnu
    btnu = 1 - btnu
def Down():
    global btnd
    btnd = 1 - btnd
def Forward():
    global btnf
    btnf = 1 - btnf
def Behind():
    global btnb
    btnb = 1 - btnb
def Left():
    global btnl
    btnl = 1 - btnl
def Right():
    global btnr
    btnr = 1 - btnr
def RotateL():
    global btny
    btny = 1 - btny
def RotateR():
    global btnv
    btnv = 1 - btnv
def Manual():
    global btnm
    btnm = 1 - btnm
def Auto():
    global btna
    btna = 1 - btna
def Gesture():
    global btng
    btng = 1 - btng
def Stop():
    global btns
    btns = 1 - btns

#Thao tác với cửa sổ
#Hiển thị Background trên cửa sổ


# Tranning hình ảnh nhận diện
# Thư viện nhận diện khuôn mặt
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
recognizer = cv2.face.LBPHFaceRecognizer_create()
recognizer.read('recognizer/trainningData.yml')

# Lấy dữ liệu từ SQLite3
def getProfile(id):
    conn = sqlite3.connect('Data.db')
    query = "SELECT * FROM Datas WHERE ID=" + str(id)
    cursor = conn.execute(query)

    profile = None

    for row in cursor:
        profile = row

    conn.close()
    return profile

a = []
#Nhận diện khuôn mặt
def faceRecognition(img):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray)
    name = []
    for (x, y, w, h) in faces:
        cv2.rectangle(img, (x, y), (x + w, y + h), (0, 255, 0), 2)

        roi_gray = gray[y:y + h, x:x + w]

        id, confidence = recognizer.predict(roi_gray)
        print(confidence)
        a.append(int(confidence))
        if (confidence < 80):
            profile = getProfile(id)
            #print(profile)
            if (profile != None):
                # cv2.putText(frame, id, (10,30), fontface, 1, (0, 0, 255), 2)
                cv2.putText(img, str(profile[1]), (x + 10, y + h + 30), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
                name = profile[1]
        else:
            cv2.putText(img, "Unkown", (x + 10, y + h + 30), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)
            name = 0


    return img, name

pid = [0.4, 0.4, 0]
pError0, pError1 = 0, 0
area = 0
Range = [20000,30000]
t = 0.7
def trackFace(bbox, pid, pError0, pError1): #Chương trình bám theo khuôn mặt
    x,y,w,h = bbox
    cx = x+w//2
    cy = y+h//2
    area = w*h
    # print(area)
    fb = 0
    if area < Range[0] and area !=0:
        fb = 10
    if area > Range[1]:
        fb = -10
    if Range[0] < area < Range[1] and area == 0:
        fb = 0

    error0 = cx - 250
    yv = pid[0]*error0 + pid[1]*(error0-pError0)
    yv = int(np.clip(yv, -100, 100))
    yv = int(yv * t)

    error1 = cy - 200
    ud = pid[0]*error1 + pid[1]*(error1-pError1)
    ud = int(np.clip(ud, -100, 100))
    ud = int(-ud * t)


    if cx==0:
        yv = 0
        error0 = 0
    if cy==0:
        ud = 0
        error1 = 0
    print(yv,ud)
    # datn.send_rc_control(0, fb, ud, yv)

    return error0, error1

#Chương trình điển khiển Drone với nút bấm
def Control():
    if btnu == 1:
        print("Up")
        # datn.send_rc_control(0, 0, speed, 0)
    if btnd == 1:
        print("Down")
        # datn.send_rc_control(0, 0, -speed, 0)
    if btny == 1:
        print("Rotate Left")
        # datn.send_rc_control(0, 0, 0, -speed)
    if btnv == 1:
        print("Rotate Right")
        # datn.send_rc_control(0, 0, 0, speed)
    if btnf == 1:
        print("Forward")
        # datn.send_rc_control(0, speed, 0, 0)
    if btnb == 1:
        print("Backward")
        # datn.send_rc_control(0, -speed, 0, 0)
    if btnl == 1:
        print("Left")
        # datn.send_rc_control(-speed, 0, 0, 0)
    if btnr == 1:
        print("Right")
        # datn.send_rc_control(speed, 0, 0, 0)
    if btns == 1:
        print("Stop")
        # datn.send_rc_control(0, 0, 0, 0)

def ControlDrone(img, lmList, p1, p2, p3, p4, p5, p6, p7, draw=True): #Điều khiển Drone bằng cử chỉ cơ thể
    x1, y1 = lmList[p1][1:]
    x2, y2 = lmList[p2][1:]
    x3, y3 = lmList[p3][1:]
    x4, y4 = lmList[p4][1:]
    x5, y5 = lmList[p5][1:]
    x6, y6 = lmList[p6][1:]
    x7, y7 = lmList[p7][1:]

    cacu1 = math.degrees(math.atan2(y2-y1,x2-x1)-math.atan2(y2-y3,x2-x3))
    cacu2 = math.degrees(math.atan2(y5-y4,x5-x4)-math.atan2(y5-y6,x5-x6))
    if cacu1<0:
        cacu1 += 360
    if cacu2<0:
        cacu2 += 360

    if 250<cacu1<290:
        print("Left")
        # datn.send_rc_control(-speed,0,0,0)

    if 80<cacu2<120:
        print("Right")
        # datn.send_rc_control(speed, 0, 0, 0)

    if 80<cacu1<120:
        print("Backward")
        # datn.send_rc_control(0, -speed, 0, 0)

    if 250<cacu2<290:
        print("Forward")
        # datn.send_rc_control(0, speed, 0, 0)

    if 170<cacu1<200:
        print("Down")
        # datn.send_rc_control(0, 0, -speed, 0)

    if 150<cacu2<180:
        print("Up")
        # datn.send_rc_control(0, 0, speed, 0)

    if draw:
        cv2.line(img, (x1, y1), (x2, y2), (255, 255, 255), 2)
        cv2.line(img, (x2, y2), (x3, y3), (255, 255, 255), 2)
        cv2.line(img, (x4, y4), (x5, y5), (255, 255, 255), 2)
        cv2.line(img, (x5, y5), (x6, y6), (255, 255, 255), 2)
        cv2.circle(img, (x1, y1), 10, (0, 255, 0), 2)
        cv2.circle(img, (x2, y2), 10, (0, 255, 0), 2)
        cv2.circle(img, (x3, y3), 10, (0, 255, 0), 2)
        cv2.circle(img, (x4, y4), 10, (0, 255, 0), 2)
        cv2.circle(img, (x5, y5), 10, (0, 255, 0), 2)
        cv2.circle(img, (x6, y6), 10, (0, 255, 0), 2)
        cv2.circle(img, (x7, y7), 10, (0, 255, 0), 2)
        cv2.putText(img, str(int(cacu1)), (x2 - 20, y2 - 20), cv2.FONT_HERSHEY_PLAIN, 2, (0, 0, 255), 2)
        cv2.putText(img, str(int(cacu2)), (x5 - 20, y5 - 20), cv2.FONT_HERSHEY_PLAIN, 2, (0, 0, 255), 2)
    # print("cacu1 =", cacu1)
    # print("cacu2 =", cacu2)

def ControlTello(lmList): # Điều khiển drone bằng bàn tay
    Ids = [4, 8, 12, 16, 20]
    # Nếu danh sách điểm trên tay khác 0
    if len(lmList) != 0:
        fingers = []
        # Ngón cái
        if lmList[Ids[0]][1] > lmList[Ids[0] - 2][1]:
            fingers.append(1)
        else:
            fingers.append(0)
        # 4 ngón còn lại
        for id in range(1, 5):
            if lmList[Ids[id]][2] < lmList[Ids[id] - 2][2]:
                fingers.append(1)
            else:
                fingers.append(0)
        totalFingers = fingers.count(1)
        print(totalFingers)
        # if totalFingers == 0:
        #     datn.send_rc_control(0, 0, 0, 0)
        # if totalFingers == 1:
        #     datn.send_rc_control(0, speed, 0, 0)
        # if totalFingers == 2:
        #     datn.send_rc_control(0, -speed, 0, 0)
        # if totalFingers == 3:
        #     datn.send_rc_control(speed, 0, 0, 0)
        # if totalFingers == 4:
        #     datn.send_rc_control(-speed, 0, 0, 0)


detector = Face.FaceDetection()
detector1 = Face.FaceMesh()
detector2 = Face.Hand()
detector3 = Face.Pose()

def update_frame():
    global canvas, photo, pError0, pError1
    _, img = video.read()
    # img = datn.get_frame_read().frame
    img = cv2.resize(img, dsize=None, fx=0.8, fy=0.85)
    if btnm==1:
        # print("K có j đâu, bấm nút cũng vô ích thôi")
        Control()
    if btna==1:
        img, name = faceRecognition(img)
        if name=="luu":
            #img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            img = detector3.findPose(img)
            lmList3, bbox3 = detector3.findPosition(img)
            if len(lmList3) != 0:
              ControlDrone(img, lmList3, 15, 11, 23, 16, 12, 24, 0)
        else:
            print("Unknown")

    if btng==1:
        img = detector2.findHands(img)
        lmList2, bbox2 = detector2.findPosition(img)
        ControlTello(lmList2)

    if btn1==1:
        img, bbox = detector.findFaces(img)
        # img, name, ct = faceRecognition(img)
        pError0, pError1 = trackFace(bbox, pid, pError0, pError1)

    if btn2==1:
        img = detector1.findFaceMesh(img)
    if btn3==1:
        img = detector2.findHands(img)
        lmList2, bbox2 = detector2.findPosition(img)
    if btn4==1:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img = detector3.findPose(img)
        lmList3, bbox3 = detector3.findPosition(img)
    else:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    photo = PIL.ImageTk.PhotoImage(image=PIL.Image.fromarray(img))
    canvas.create_image(0,0, image = photo, anchor=tkinter.NW)
    window.after(10, update_frame)

update_frame()
window.mainloop()

# datn.streamoff()
# datn.land()
# video.release()
# cv2.destroyAllWindows()

